"""make price_observation price nullable

Revision ID: 46b229a2f7db
Revises: a5aa42768514
Create Date: 2026-08-02 04:01:03.677910
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46b229a2f7db'
down_revision: Union[str, None] = 'a5aa42768514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price_observations', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price_observations', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###
