"""make product sku nullable

Revision ID: a5aa42768514
Revises: b7c80dfcff7b
Create Date: 2026-07-23 22:52:36.095789
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a5aa42768514'
down_revision: Union[str, None] = 'b7c80dfcff7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'sku',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
